name: lanpartyguru
services:
  languru:
    image: node:24
    volumes:
      - ./app:/home/node
    command: bash
    tty: true
    user: node
    environment:
      - WEB_API_KEY_FILE=/run/secrets/web_api_key
      - TZ=Europe/Berlin
    secrets:
      - web_api_key
    working_dir: /home/node/lpguru
    networks:
      - frontend

secrets:
  web_api_key:
    file: api_key.txt

networks:
  frontend:
    name: lpp_frontend
