name: lanpartyguru
services:
  languru:
    image: node:20
    volumes:
      - ./app:/home/node
    command: bash
    tty: true
    user: node
    working_dir: /home/node/lpguru
    ports:
      - "3000:3000"

